name: Daily R Script

on:
  schedule:
    - cron: "20 17 * * *"

jobs:
  run_r_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Setup R environment
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.1.3'
          include_packages: tidyverse@2.0.0,scholar@0.2.4,glue@1.6.2,rentrez@1.2.3,XML@3.99-0.9,tokenizers@0.2.1,stopwords@2.3

      - name: Install dependencies
        run: |
          sudo apt-get install -y libcurl4-openssl-dev
          sudo apt-get install libharfbuzz-dev libfribidi-dev
          sudo apt-get install libfontconfig1-dev 
          Rscript -e 'install.packages(c("tidyverse","scholar","glue","rentrez","XML","tokenizers","stopwords"))'
      
      - name: Run R script
        run: Rscript scholar.R

      - name: Add new files in data folder
        run: |
          git add -A data
          git diff --quiet && git diff --staged --quiet || git commit -m "Updated data files"
          git push origin ${{ github.ref }}
