name: Daily R Script

on:
  schedule:
    - cron: "55 18 * * *"

jobs:
  run_r_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Setup R environment
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: '4.2.3'
          include_packages: tidyverse,scholar,glue,rentrez,XML,tokenizers,stopwords

      - name: Install dependencies
        run: |
          Rscript -e 'install.packages(c("tidyverse","scholar","glue","rentrez","XML","tokenizers","stopwords"))'
      
      - name: Run R script
        run: Rscript scholar.R

      - name: Add new files in data folder
        run: |
          git add -A data
          git diff --quiet && git diff --staged --quiet || git commit -m "Updated data files"
          git push origin ${{ github.ref }}
